LICENSE.md, README.md
This merge request adds the GPL-3.0 License and a small license notice in README.md.
I'd like to ask all current contributors for their approval regarding the license before merging this in.
Please let me know if you agree with adding this license to Replanetizer, or if you'd like to see a different license (or no license) instead.
The previous contents of LICENCE.md have been moved to the notice in README.md
Why GPL-3.0?
------------
GPL license ensures Replanetizer will stay open source, even when
included in another application. A small overview about GPL-3.0
can be found at https://choosealicense.com/licenses/gpl-3.0/.
Why add a license at all?
-------------------------
Adding a license ensures (future) contributors to Replanetizer know what
will happen to their code after …
=> Add the GPL-3.0 License.

LibReplanetizer/Level Objects/Engine/TerrainFragment.cs, LibReplanetizer/Models/TerrainModel.cs, LibReplanetizer/Serializers/ModelWriter.cs, Replanetizer/CustomControls/CustomGLControl.cs, Replanetizer/Forms/LevelExportWindow.Designer.cs, Replanetizer/Forms/LevelExportWindow.cs, Replanetizer/Forms/LevelExportWindow.resx, Replanetizer/Forms/Main.Designer.cs, Replanetizer/Forms/Main.cs, Replanetizer/Forms/TextureViewer.Designer.cs, Replanetizer/Forms/TextureViewer.cs, Replanetizer/Forms/TextureViewer.resx, Replanetizer/Replanetizer.csproj
- Added exporting whole levels as an `*.obj` file with 4 different modes of how the objects are combined
- Added dialog to export texture so the user can specify a path
- Added export all textures button, useful in combination with exporting the whole level
- Fixed a bug where if you deactivated that ties, shrubs etc are visible and then loaded a new level, the fact that GLControl reactivated those visibilities was not reflected in the UI
=> Level Export feature

Replanetizer/CustomControls/CustomGLControl.cs, Replanetizer/Forms/Main.Designer.cs, Replanetizer/Forms/Main.cs
- Added drawing the skybox, it is always centered around the camera (if I am not wrong that is how the skybox worked in the game too) and is always drawn behind everything, some skyboxes are transparent multilayered, however, these do not look right yet since we have no transparency sorting
- Added the option to enable transparency for mobies, since there is no transparency sorting other mobies may be invisible behind it but it looks good as an optional thing
-----
I will keep this PR up for a bit and merge myself if no one has any suggestions.
=> Skybox and Transparent Mobies

LibReplanetizer/Headers/ChunkHeader.cs, LibReplanetizer/Headers/GameplayHeader.cs, LibReplanetizer/Level Objects/GameType.cs, LibReplanetizer/Level Objects/Gameplay/Moby.cs, LibReplanetizer/Level.cs, LibReplanetizer/Parsers/ChunkParser.cs, LibReplanetizer/Parsers/EngineParser.cs, LibReplanetizer/Serializers/ChunkSerializer.cs, LibReplanetizer/Serializers/GameplaySerializer.cs, Replanetizer/CustomControls/CustomGLControl.cs, Replanetizer/Forms/Main.cs
- Fixed saving and loading Rac 2 and 3 levels
- Fixed a crash on Grelbin, Yeedil and Rac 3's Insomniac Museum where for some reason there is no collision data in some of the chunks
- Fixed collision bytes being read further than they actually are
-------
I will keep this PR up for a bit and merge myself if no one has any suggestions.
=> Fixing Saving and Loading Levels

LibReplanetizer/DataFunctions.cs, LibReplanetizer/Headers/EngineHeader.cs, LibReplanetizer/Headers/GameplayHeader.cs, LibReplanetizer/Headers/Headers.cs, LibReplanetizer/Level Objects/Engine/Terrain.cs, LibReplanetizer/Level Objects/Gameplay/Cuboid.cs, LibReplanetizer/Level Objects/Gameplay/Cylinder.cs, LibReplanetizer/Level Objects/Gameplay/LevelVariables.cs, LibReplanetizer/Level Objects/Gameplay/Moby.cs, LibReplanetizer/Level Objects/Gameplay/Sphere.cs, LibReplanetizer/Level Objects/Gameplay/Type0C.cs, LibReplanetizer/Level.cs, LibReplanetizer/Parsers/ChunkParser.cs, LibReplanetizer/Parsers/EngineParser.cs, LibReplanetizer/Parsers/GameplayParser.cs, LibReplanetizer/Parsers/RatchetFileParser.cs, LibReplanetizer/Serializers/ChunkSerializer.cs, LibReplanetizer/Serializers/EngineSerializer.cs, LibReplanetizer/Serializers/GameplaySerializer.cs, LibReplanetizer/Serializers/ModelWriter.cs, LibReplanetizer/Serializers/SerializerFunctions.cs, Replanetizer/Frames/LevelFrame.cs
This PR fixes most major serialization errors. I did this by serializing and then looking at the diffs of the output to the original files. The result is not perfect especially as things like languages, shrub models etc are not parsed/serialized 100% accurately. However, the output is good enough that RaC 1 and 2 are able to load the files. I did not test whether RaC 3 or Deadlocked are able to do so but Deadlocked most likely isn't yet as there is still a lot not being parsed.
Additionally, since I got a bit of an insight in what we currently parse incorrectly some things have changed. For example, there are now a lot more level variables being parsed. Further I noticed that there is another set of pointers in the terrain in Deadlocked.
Further, as suggested by chaoticgd, this PR fixes …
=> Serialization Fixes

Replanetizer/Frames/ModelFrame.cs
I couldn't find this functionality elsewhere in the UI/code, so I added a button below "Export model" to export all textures associated with the selected model to a folder.
=> Model viewer - Add button to export all textures for the selected model

LibReplanetizer/Level Objects/Engine/Light.cs, LibReplanetizer/Level Objects/Engine/Shrub.cs, LibReplanetizer/Level Objects/Engine/Terrain.cs, LibReplanetizer/Level Objects/Engine/Tie.cs, LibReplanetizer/Level.cs, LibReplanetizer/Serializers/SerializerFunctions.cs, Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/PropertyFrame.cs
This PR includes:
- Updated property names and information for ties, shrubs, terrain fragments and lights.
- Added support for more types in the property frame.
- Fixed a bug where tools only work if the mouse remains on the arrows.
- Fixed a bug where changes in a property frame do not invalidate the level frame.
- Fixed a bug where saving a level to a non existent file causes a crash.
With this we now have a lot more lighting and shading information available. I plan to write shaders for each class (ties, mobies, shrubs etc) to match the visuals in replanetizer with the visuals of the game in a future PR.
=> Property related Changes

Replanetizer/Frames/LevelFrame.cs
I added an overlay which displays the camera's position and rotation in the level. It can be toggled under the Render menu.
=> Display camera info

Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/ModelFrame.cs, Replanetizer/Utils/KeyHeldHandler.cs, Replanetizer/Utils/MouseGrabHandler.cs
After I added the infinite drag feature in #21, I realized it messed with rotation in the model viewer (trying to rotate in the model viewer would also rotate the level). It now will check if the mouse is hovering directly over the level frame before allowing rotation. I also added similar rotation functionality to the model viewer.
=> Fix level viewer greedy rotation

Replanetizer/Frames/LevelFrame.cs
This adds buttons with which you can export a list of all class IDs present in a level for a certain object type. This was requested by people on Discord.
Note that the second commit contains some removal of trailing whitespaces and whitespaces after casts are made consistent there.
I will just merge, this PR just adds a small feature and does not interact with anything else.
=> Export Class IDs Lists

Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/ModelFrame.cs, Replanetizer/Frames/PropertyFrame.cs, Replanetizer/Utils/FramebufferRenderer.cs
This implements some changes suggested by CreepNT.
- Fixes a crash when variables in PropertyFrame are null.
- Adds a framerate counter to the camera info overlay.
- Fixes framebuffers being allocated every frame which caused a heavy memory leak when pressing left click.
While the third fix improves performance when pressing left click, the GetObjectAtScreenPosition() function is still too costly and causes performance drops. However, this will be time consuming to fix.
=> Suggested changes by CreepNT

LibReplanetizer/Level Objects/Engine/Light.cs, LibReplanetizer/Level Objects/Engine/Shrub.cs, LibReplanetizer/Level Objects/Engine/Tie.cs, LibReplanetizer/Models/ShrubModel.cs, LibReplanetizer/Parsers/EngineParser.cs, LibReplanetizer/Serializers/EngineSerializer.cs, Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/LightsFrame.cs
This replaces the light config frame with a lights frame. The lights frame additionally allows to modify all directional lights.
- Named directional light index variables in ties and shrubs.
- Fixed serialization of engine collision, shrubs and ties.
As far as I can tell, the engine file for RaC 1 should now get serialized 100% accurately.
=> Lights and Serialization Fixes.

Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/ModelFrame.cs, Replanetizer/Shaders/fs.glsl, Replanetizer/Shaders/vs.glsl, Replanetizer/Utils/FramebufferRenderer.cs
This adds MSAA support which is set to 2x by default. On an RTX 3070 Ti, I cannot measure any performance difference between Off and 32x MSAA.
I ask OpenGL what the maximum supported msaa level is and all supported levels are then exposed through the settings.
Part of this implementation required the fragment shader to be made as cheap as possible, this meant I moved as many computations to the vertex shader as possible. Most likely, the game did it the same way so this is fine. 
Further, I had to rewrite the fog shading since that is now done in the vertex shader. The fog looks very similar to the game now I would say. However, I said that many times before when that wasn't the case so what do I know.
The model viewer uses the same msaa level as the levelFrame.
Closes #47
=> MSAA support

LibReplanetizer/Level Objects/LevelObject.cs, Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/ModelFrame.cs, Replanetizer/Frames/PropertyFrame.cs, Replanetizer/Tools/BasicTransformTool.cs, Replanetizer/Tools/PivotPositioning.cs, Replanetizer/Tools/RotationTool.cs, Replanetizer/Tools/ScalingTool.cs, Replanetizer/Tools/SpecialTransformTool.cs, Replanetizer/Tools/Tool.cs, Replanetizer/Tools/ToolType.cs, Replanetizer/Tools/Toolbox.cs, Replanetizer/Tools/TransformSpace.cs, Replanetizer/Tools/TransformationSpace.cs, Replanetizer/Tools/TranslationTool.cs, Replanetizer/Tools/VertexTranslationTool.cs, Replanetizer/Utils/EnhancedEnum.cs, Replanetizer/Utils/Keymap.cs, Replanetizer/Utils/RenderableBuffer.cs, Replanetizer/Utils/Selection.cs
I have added a bunch of features related to multi-selection!
- Left click to toggle selection of a single object
- Shift+left click to toggle selection of multiple objects
There are two new buttons in the menu bar which cycle through the following options:
- Transform space - transform along:
- Global (world) axes
- Local (object) axes
- Pivot positioning - pivot multiple selected objects about:
- The median point of the objects
- Each object's origin
In the process of creating this feature, I've also created some classes to make it easier to program in a key-agnostic way and to move keys out of Tick functions and into a single area.
There is an immutable dictionary `Keymap.DEFAULT_KEYMAP` which holds the current keymappings. In the future, this could be expanded to allow for user-define …
=> Add multi-select

LibReplanetizer/DataFunctions.cs, LibReplanetizer/Level Objects/Gameplay/LanguageData.cs, LibReplanetizer/Level.cs, LibReplanetizer/Parsers/GameplayParser.cs, LibReplanetizer/Serializers/GameplaySerializer.cs
Previously we parsed language data as ASCII characters which meant that any character outside the ASCII range got parsed as a ?. Because of this dataloss the gameplay_ntsc file could not be reconstructed. This PR fixes that, and also parses the secondary id data in the "header" portion of the language data. I believe this is used to indicate soundclips that are supposed to be played during helpdesk messages.
Notably this will break the previous string viewer UI, but that doesn't seem to be reimplemented in the imgui version, so I guess it's fine.
=> Fixes serialization of language

LibReplanetizer/Serializers/ModelWriter.cs, Replanetizer/Frames/ModelFrame.cs
The skybox now appears in the model viewer (though it is not rendered).
The skybox can be exported for both `.obj` and `.dae` formats. The `.dae` format also includes the vertex colors. 
Since I had to implement vertex colors for collada, I also added vertex color export for terrain,
=> Skybox Export and Vertex Color Export in Collada

.github/workflows/build.yml, LibReplanetizer/Level Objects/Gameplay/LevelVariables.cs, LibReplanetizer/Level Objects/QuaternionTypeConverter.cs, LibReplanetizer/LibReplanetizer.csproj, LibReplanetizer/Models/MobyModel.cs, LibReplanetizer/Models/Model.cs, LibReplanetizer/Models/ShrubModel.cs, LibReplanetizer/Models/Texture.cs, LibReplanetizer/Models/TextureConfig.cs, LibReplanetizer/Models/TieModel.cs, LibReplanetizer/Utilities.cs, README.md, Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/ModelFrame.cs, Replanetizer/Frames/PropertyFrame.cs, Replanetizer/Frames/TextureFrame.cs, Replanetizer/Frames/UpdateInfoFrame.cs, Replanetizer/ModelLists/ModelLists.cs, Replanetizer/Replanetizer.csproj, Replanetizer/Shaders/fs.glsl, Replanetizer/Utils/RenderableBuffer.cs, Replanetizer/Utils/ShaderIDTable.cs, Replanetizer/Utils/TextureIO.cs, Replanetizer/Window.cs
- This PR migrates the code base to .Net 6. Closes #32 
- Also any object that is not a moby now uses dithering to achieve transparency. This is supposed to be a cheap solution which is going to be replaced by proper transparency sometime in the future.
- The transparency issue that occurred in RaC 3 should now be mostly fixed. This also applies to exported textures.
- Added additional level variables. This was made possible by CreepNT and Badger41. (Only 2 variables are unknown at this point excluding Deadlocked)
=> .Net 6, dithered transparency, RaC 3 transparency bugfixes and new level variables.

LibReplanetizer/Models/Animation/Frame.cs, Replanetizer/Frames/LevelFrame.cs
There were some more issues:
- Some textures specify that they have more mipmaps than they actually have.
- Deadlocked ports to UYA sometimes have broken animation frame counts. (This may be related to DL animations being different?)
=> More fixes for custom UYA MP levels.

LibReplanetizer/Level Objects/Engine/Shrub.cs, LibReplanetizer/Level Objects/Engine/Tie.cs, LibReplanetizer/Level Objects/Gameplay/LevelVariables.cs, LibReplanetizer/Level Objects/Gameplay/Moby.cs, LibReplanetizer/LibReplanetizer.csproj, LibReplanetizer/Models/MobyModel.cs, LibReplanetizer/Models/TextureConfig.cs, LibReplanetizer/Serializers/Exporters/ColladaExporter.cs, LibReplanetizer/Serializers/Exporters/ExporterUtils.cs, LibReplanetizer/Serializers/Exporters/WavefrontExporter.cs, LibReplanetizer/Utilities.cs, Replanetizer/Frames/LevelFrame.cs, Replanetizer/Frames/ModelFrame.cs, Replanetizer/Frames/PropertyFrame.cs, Replanetizer/Replanetizer.csproj, Replanetizer/Shaders/fs.glsl, Replanetizer/Shaders/skyvs.glsl, Replanetizer/Shaders/vs.glsl, Replanetizer/Tools/BasicTransformTool.cs, Replanetizer/Tools/RotationTool.cs, Replanetizer/Tools/ScalingTool.cs, Replanetizer/Tools/Tool.cs, Replanetizer/Tools/TransformToolData.cs, Replanetizer/Tools/TranslationTool.cs, Replanetizer/Utils/Camera.cs, Replanetizer/Utils/RenderableBuffer.cs, Replanetizer/Utils/ShaderIDTable.cs, Replanetizer/Window.cs
Renderer:
- Texture wrapping modes based on the texture config are now included.
- Fixed fog rendering.
- Fixed light intensity scaling.
Moby spawn flags:
- Replaced the enum based spawn flags with a bitmask based one
- Added meaning for each bit (Thanks to Trippy Contrails Connoisseur)
Transformation tools:
- Translation tool now behaves like in Blender
- Scaling and rotation tools are now properly clickable.
- Scaling now works correctly (however local transformation space is always used)
Added the possibility of adding descriptions to fields which are then displayed in a property frame.
Models export include texture wrapping modes now. (However, Blender ignores them)
Closes #55
Closes #61
=> Improved renderer, spawn flags and improved transformation tools.

LibReplanetizer/LibReplanetizer.csproj, Replanetizer/Replanetizer.csproj, Replanetizer/Utils/TextureIO.cs
The mission textures were used when exporting the mobyload textures which could also crash Replanetizer when there were more mobyload textures than missions.
=> Fix crash when exporting textures

Replanetizer/Utils/CrossFileDialog.cs
I noticed the windows implementation of `CrossFileDialog` was returning the currently entered string even when pressing cancel, gone ahead and made it return an empty string in that case. I've not tested the `KDialog` or `Zenity` implementation as I currently don't have an Linux install.
I've also noticed that whenever CrossFileDialog is used, it checks to make sure the string isn't empty so i assume that's the desired behaviour here.
=> Return empty string on pressing "cancel" on windows file dialog
